/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;

/**
 *
 * @author motaz
 */
public class ModifierAppartements extends javax.swing.JPanel {

    /**
     * Creates new form ModifierAppartements
     */
    private int Id =-1;
    private void update(){
    try{
                System.out.println("In");
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                Statement stmt = con.createStatement();
                String SQL = "SELECT * FROM APPARTEMENT WHERE ID = "+Id;
                ResultSet rs = stmt.executeQuery(SQL);
                while(rs.next()){
                String Add = rs.getString("ADDRESS");
                String Des = rs.getString("DESCRIP");
                int nbr = rs.getInt("NUMBEROFROOMS");
                int pr = rs.getInt("PRIX");
                int size = rs.getInt("SIZEINSQUAREMETERS");
                String st = rs.getString("STATUT");
                IdL.setText(Id+"");
                AdL.setText(Add);
                NbL.setText(nbr+"");
                PrF.setText(pr+"");
                DeF.setText(Des);
                SiL.setText(size+"");
                if(st.equals("Available") || st.equals("available")){
                StC.setSelectedItem("Available");
                }
                else{StC.setSelectedItem("Reserved");}
                
                }
                }catch(SQLException err){
                System.out.println(err.getMessage());
            }
    }
    public ModifierAppartements() {
        initComponents();
        System.out.println("not good");
        
    }
    public ModifierAppartements(int id){
        initComponents();
        System.out.println("in1");
        
        this.Id=id;
        update();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IdL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AdL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NbL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SiL = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        StC = new javax.swing.JComboBox<>();
        PrF = new javax.swing.JTextField();
        DcB = new javax.swing.JButton();
        PrB = new javax.swing.JButton();
        StB = new javax.swing.JButton();

        jLabel5.setText("ADMIN");

        jLabel1.setText("ID :");

        IdL.setText("id");

        jLabel3.setText("ADDRESS :");

        AdL.setText("adr");

        jLabel6.setText("Number of rooms :");

        NbL.setText("nbrR");

        jLabel8.setText("Size :");

        SiL.setText("size");

        jLabel10.setText("Describtion :");

        DeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeFActionPerformed(evt);
            }
        });

        jLabel11.setText("Price :");

        jLabel12.setText("Status");

        StC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available" , "Reserved" }));

        PrF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrFActionPerformed(evt);
            }
        });

        DcB.setText("Change");
        DcB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcBActionPerformed(evt);
            }
        });

        PrB.setText("Change");
        PrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrBActionPerformed(evt);
            }
        });

        StB.setText("Change");
        StB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DcB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DeF, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IdL)
                                .addComponent(AdL)
                                .addComponent(NbL)
                                .addComponent(SiL)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(106, 106, 106))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(107, 107, 107)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PrF)
                                .addComponent(StC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PrB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(StB, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IdL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AdL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NbL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SiL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DcB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(PrF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(StC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StB)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeFActionPerformed

    private void PrFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrFActionPerformed

    private void StBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StBActionPerformed
        try{
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                
                String sql = "UPDATE APPARTEMENT SET STATUT = ? WHERE ID = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);

                // Set the new email and the id of the client you want to update
                Object StO = StC.getSelectedItem();
                String StS = StO.toString();
                pstmt.setString(1, StS);
                pstmt.setInt(2, Id); // e.g., client with ID 1

                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Updated rows: " + rowsAffected);

                pstmt.close();
                con.close();
                
                
                
                
                
            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
            this.update();
    }//GEN-LAST:event_StBActionPerformed

    private void DcBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcBActionPerformed
        try{
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                
                String sql = "UPDATE APPARTEMENT SET DESCRIP = ? WHERE ID = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);

                // Set the new email and the id of the client you want to update
                String Des = DeF.getText();
                pstmt.setString(1, Des);
                pstmt.setInt(2, Id); // e.g., client with ID 1

                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Updated rows: " + rowsAffected);

                pstmt.close();
                con.close();
                
                
                
                
                
            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
            this.update();
    }//GEN-LAST:event_DcBActionPerformed

    private void PrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrBActionPerformed
        try{
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                
                String sql = "UPDATE APPARTEMENT SET PRIX = ? WHERE ID = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);

                // Set the new email and the id of the client you want to update
                String prix = PrF.getText();
                pstmt.setString(1, prix);
                pstmt.setInt(2, Id); // e.g., client with ID 1

                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Updated rows: " + rowsAffected);

                pstmt.close();
                con.close();
                
                
                
                
                
            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
            this.update();
    }//GEN-LAST:event_PrBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdL;
    private javax.swing.JButton DcB;
    private javax.swing.JTextField DeF;
    private javax.swing.JLabel IdL;
    private javax.swing.JLabel NbL;
    private javax.swing.JButton PrB;
    private javax.swing.JTextField PrF;
    private javax.swing.JLabel SiL;
    private javax.swing.JButton StB;
    private javax.swing.JComboBox<String> StC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
