/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author motaz
 */
public class ConfirmReservation2 extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmReservation2
     */
    public ConfirmReservation2() {
        initComponents();
    }
    String GetCookie(){
        try{
                File myObj = new File("cookie.txt");
                Scanner Reader = new Scanner(myObj);
                String cookies = Reader.nextLine();
                Reader.close();
                return cookies;
            }
            catch(FileNotFoundException e){
                System.out.println(e.getMessage());
                return ("-1");
            }
        }
    ConfirmReservation2(String id, String Checkin , String Checkout){
        initComponents();
        try{
            String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
            String uName = "root";
            String uPass = "root";
            
            Connection con = DriverManager.getConnection(host, uName, uPass);
            Statement stmt = con.createStatement();
            
            
            String SQL ="SELECT ADDRESS, PRIX, NumberOfRooms, SizeInSquareMeters FROM appartement WHERE ID = " + id ;
            
            ResultSet rs = stmt.executeQuery(SQL);
            IDL.setText(id);
            
            while(rs.next()){
                Loc.setText(rs.getString("ADDRESS"));
                Num.setText(rs.getString("NumberOfRooms"));
                SizeL.setText(rs.getString("SizeInSquareMeters"));
                PriceF.setText(rs.getString("PRIX"));
                CheckinF.setText(Checkin);
                CheckoutF.setText(Checkout);
                
                
            }
            
        }
        catch(SQLException err){
            System.out.println(err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();
        checkin = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        Loc = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        SizeL = new javax.swing.JLabel();
        CheckoutF = new javax.swing.JLabel();
        CheckinF = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        PriceF = new javax.swing.JLabel();
        IDL = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("RESERVATION CONFIRMATION");

        Location.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Location.setText("Location : ");

        Number.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Number.setText("Number of rooms: ");

        Size.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Size.setText("Size : ");

        checkin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        checkin.setText("Check-In: ");

        checkout.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        checkout.setText("Check-out: ");

        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        Price.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Price.setText("Price");

        IDL.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PriceF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Loc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SizeL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckoutF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckinF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(check)
                .addGap(61, 61, 61)
                .addComponent(IDL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Location))
                    .addComponent(Loc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number)
                    .addComponent(Num))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Size)
                    .addComponent(SizeL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkin)
                    .addComponent(CheckinF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkout)
                    .addComponent(CheckoutF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(PriceF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check)
                    .addComponent(IDL))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        try{
            String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
            String uName = "root";
            String uPass = "root";

            Connection con = DriverManager.getConnection(host, uName, uPass);
            Statement stmt = con.createStatement();

            String cookies = GetCookie();
            if(cookies.equals("-1")){

                JOptionPane.showMessageDialog(null,"You have to login first");

            }
            else{
                String SQLID = "SELECT MAX(ID) FROM appartement";
                ResultSet rsid = stmt.executeQuery(SQLID);
                int ID;
                if (rsid.next()) {
                    ID = rsid.getInt(1) + 1;

                } else {
                    ID = 1;
                }

                String SQL = "SELECT ID FROM CLIENTS WHERE COOKIE = '" + cookies + "'";
                ResultSet rs = stmt.executeQuery(SQL);
                if(rs.next()){
                    String SQLI = "INSERT INTO reservation(ID, ID_CLIENT, ID_APPARTEMENT, DATEDEBUT, DATEFIN) VALUES (" + ID + ", "
                    + rs.getString("ID") + ", " + IDL.getText() + ", '"
                    + CheckinF.getText() + "', '"
                    + CheckoutF.getText() + "')";
                    stmt.executeUpdate(SQLI);
                    JOptionPane.showMessageDialog(null, "Reservation confirmed successfully!");
                }
                else{
                    JOptionPane.showMessageDialog(null,"You have to login first");
                }
            }

        }
        catch(SQLException err){
            System.out.println(err.getMessage());
        }

    }//GEN-LAST:event_checkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckinF;
    private javax.swing.JLabel CheckoutF;
    private javax.swing.JLabel IDL;
    private javax.swing.JLabel Loc;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel PriceF;
    private javax.swing.JLabel Size;
    private javax.swing.JLabel SizeL;
    private javax.swing.JButton check;
    private javax.swing.JLabel checkin;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
void setVisible() {
        this.setVisible(true);
    }
}
