/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author motaz
 */
public class ModifierClients2 extends javax.swing.JPanel {

    /**
     * Creates new form ModifierClients2
     */
    private static String email;
    public ModifierClients2() {
        initComponents();
    }
    private void update(){
    
        try{
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                Statement stmt = con.createStatement();
                String SQL = "SELECT * FROM CLIENTS WHERE EMAIL = '"+email+"'";
                ResultSet rs = stmt.executeQuery(SQL);
                while(rs.next()){
                String Email = rs.getString("EMAIL");
                String tel = rs.getString("TELEPHONE");
                int cl = rs.getInt("CLASS");
                int iD = rs.getInt("ID");
                EmailL.setText(Email);
                Tele.setText(tel);
                id.setText(iD+"");
                classL.setText(cl+"");
                
                }
                }catch(SQLException err){
                System.out.println(err.getMessage());
            }
        
    }
    public ModifierClients2(String mail){
        initComponents();
        System.out.println(mail+"1");
        this.email=mail;
        System.out.println(email+"2");
                System.out.println("in");
        this.update();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IdF = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ClassF = new javax.swing.JComboBox<>();
        classL = new javax.swing.JLabel();
        ClassB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tele = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmailL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        IdB.setText("Change");
        IdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerIdB(evt);
            }
        });

        jLabel3.setText("ID :");

        IdF.setText("New ID");
        IdF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdFMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IdFMouseExited(evt);
            }
        });
        IdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFActionPerformed(evt);
            }
        });

        id.setText("id");

        jLabel5.setText("ADMIN");

        ClassF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "       0", "       1", "       2" }));
        ClassF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassFActionPerformed(evt);
            }
        });

        classL.setText("class");

        ClassB.setText("Change");
        ClassB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerClassB(evt);
            }
        });

        jLabel2.setText("Class : ");

        Tele.setText("Telephone");

        jLabel4.setText("Numero : ");

        EmailL.setText("Email");

        jLabel1.setText("Email : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tele, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ClassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(ClassB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IdB)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EmailL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tele))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClassB)
                    .addComponent(classL)
                    .addComponent(ClassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id)
                    .addComponent(IdB)
                    .addComponent(IdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChangerIdB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangerIdB
        try{
                int ID = Integer.parseInt(IdF.getText());
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                
                String sql = "UPDATE CLIENTS SET ID = ? WHERE EMAIL = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);

                // Set the new email and the id of the client you want to update
                pstmt.setString(2, this.email);
                pstmt.setInt(1, ID); // e.g., client with ID 1

                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Updated rows: " + rowsAffected);

                pstmt.close();
                con.close();
                
                
                
                
                
            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
            this.update();
    }//GEN-LAST:event_ChangerIdB

    private void IdFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdFMouseClicked
        
        if(IdF.getText().equals("")){
            IdF.setText("New ID");}
    }//GEN-LAST:event_IdFMouseClicked

    private void IdFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdFMouseExited
        if(IdF.getText().equals("")){
            IdF.setText("New ID");}
    }//GEN-LAST:event_IdFMouseExited

    private void IdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFActionPerformed

    private void ChangerClassB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangerClassB
        try{
                int cl = Integer.parseInt(classL.getText());
                Object classSelected = ClassF.getSelectedItem();
                String classString =classSelected.toString();
                classString = classString.strip();
                System.out.println(classString);
                
                try{
                cl = Integer.parseInt(classString);
                }catch(Exception e){
                System.out.println("Sad life");
            }
                
                String host = "jdbc:mysql://127.0.0.1:3306/locationappartement";
                String uName = "root";
                String uPass = "root";

                Connection con = DriverManager.getConnection(host, uName, uPass);
                
                
                System.out.println(cl);
                String sql = "UPDATE CLIENTS SET CLASS = ? WHERE EMAIL = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);

                // Set the new email and the id of the client you want to update
                pstmt.setString(2, this.email);
                pstmt.setInt(1, cl); // e.g., client with ID 1

                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Updated rows: " + rowsAffected);

                pstmt.close();
                con.close();
                
                
                
                
                
                
                
            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
        this.update();
    }//GEN-LAST:event_ChangerClassB

    private void ClassFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClassB;
    private javax.swing.JComboBox<String> ClassF;
    private javax.swing.JLabel EmailL;
    private javax.swing.JButton IdB;
    private javax.swing.JTextField IdF;
    private javax.swing.JLabel Tele;
    private javax.swing.JLabel classL;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
