/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class SearchResult2 extends javax.swing.JPanel {

    /**
     * Creates new form SearchResult2
     */
    public SearchResult2() {
        initComponents();
    }
    SearchResult2(ResultSet rs, String Checkin, String Checkout) {
        initComponents(); 
        
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(contentPanel);
        
        try {
            boolean hasResults = false;
            
            
            while(rs.next()){
                hasResults = true;
                String id = rs.getString("ID");
                String address = rs.getString("ADDRESS");
                String price = rs.getString("Prix");
                String size = rs.getString("SizeInSquareMeters");
                String description = rs.getString("DESCRIP");
                
                
                JPanel apartmentPanel = new JPanel();
                apartmentPanel.setPreferredSize(new Dimension(650, 50));
                apartmentPanel.setMaximumSize(new Dimension(650, 50));
                apartmentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(200, 200, 200)));
                apartmentPanel.setBackground(Color.white);
                apartmentPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                
                
                JLabel infoLabel = new JLabel();
                infoLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                infoLabel.setText("ID: " + id + " - " + address + ", " + size + " - $" + price + "\n" + description);
                
                apartmentPanel.add(infoLabel);
                
                
                JButton reserveButton = new JButton("Reserve");
                reserveButton.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                reserveButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        new ConfirmReservation(id, Checkin, Checkout).setVisible();
                        
                    }
                });
                
                apartmentPanel.add(reserveButton);
                contentPanel.add(apartmentPanel);
                
                
                JPanel spacer = new JPanel();
                spacer.setPreferredSize(new Dimension(650, 5));
                spacer.setMaximumSize(new Dimension(650, 5));
                spacer.setOpaque(false);
                contentPanel.add(spacer);
                
                System.out.println("Added apartment: " + address);
            }
            
            // If no apartments found
            if (!hasResults) {
                JPanel noResultsPanel = new JPanel();
                noResultsPanel.setPreferredSize(new Dimension(650, 50));
                noResultsPanel.setBackground(Color.white);
                
                JLabel noResultsLabel = new JLabel("No apartments found matching your criteria");
                noResultsLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                noResultsLabel.setForeground(Color.RED);
                
                noResultsPanel.add(noResultsLabel);
                contentPanel.add(noResultsPanel);
            }
            
            contentPanel.revalidate();
            contentPanel.repaint();
        }
        catch(SQLException err){
            System.out.println("SQL Error: " + err.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();

        List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
