import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anasm
 */
public class SearchResult extends javax.swing.JFrame {

    /**
     * Creates new form SearchResult
     */
    public SearchResult() {
        initComponents();
    }

    SearchResult(ResultSet rs, String Checkin, String Checkout) {
        initComponents(); // Initialize components first
        
        // Replace the JList with a JPanel
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(contentPanel);
        
        try {
            boolean hasResults = false;
            
            // Add apartment details from result set
            while(rs.next()){
                hasResults = true;
                String id = rs.getString("ID");
                String address = rs.getString("ADDRESS");
                String price = rs.getString("Prix");
                String size = rs.getString("SizeInSquareMeters");
                String description = rs.getString("DESCRIP");
                
                // Create panel for this apartment
                JPanel apartmentPanel = new JPanel();
                apartmentPanel.setPreferredSize(new Dimension(650, 50));
                apartmentPanel.setMaximumSize(new Dimension(650, 50));
                apartmentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(200, 200, 200)));
                apartmentPanel.setBackground(Color.white);
                apartmentPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                
                // Create label for apartment info
                JLabel infoLabel = new JLabel();
                infoLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                infoLabel.setText("ID: " + id + " - " + address + ", " + size + " - $" + price + "\n" + description);
                
                apartmentPanel.add(infoLabel);
                
                // Create Reserve button
                JButton reserveButton = new JButton("Reserve");
                reserveButton.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                reserveButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        new ConfirmReservation(id, Checkin, Checkout).setVisible();
                    }
                });
                
                apartmentPanel.add(reserveButton);
                contentPanel.add(apartmentPanel);
                
                // Add some space between items
                JPanel spacer = new JPanel();
                spacer.setPreferredSize(new Dimension(650, 5));
                spacer.setMaximumSize(new Dimension(650, 5));
                spacer.setOpaque(false);
                contentPanel.add(spacer);
                
                System.out.println("Added apartment: " + address);
            }
            
            // If no apartments found
            if (!hasResults) {
                JPanel noResultsPanel = new JPanel();
                noResultsPanel.setPreferredSize(new Dimension(650, 50));
                noResultsPanel.setBackground(Color.white);
                
                JLabel noResultsLabel = new JLabel("No apartments found matching your criteria");
                noResultsLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                noResultsLabel.setForeground(Color.RED);
                
                noResultsPanel.add(noResultsLabel);
                contentPanel.add(noResultsPanel);
            }
            
            // Update UI
            contentPanel.revalidate();
            contentPanel.repaint();
        }
        catch(SQLException err){
            System.out.println("SQL Error: " + err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
